### ISSUE TITLE
issue that I encountered while using your Repository. 

### ISSUE THREAD

**Issue by pizzzamaster007** [msoczi/football_predictions#2]
File "C:\Users\Private\football_predictions-master\football_preds\lib\site-packages\pandas\io\html.py", line 552, in _parse_tables
    raise ValueError("No tables found")
ValueError: No tables found

I understand that maintaining an open-source project can be demanding, and I genuinely appreciate the effort you've put into it, Thank you

**Comment by msoczi** [comment]
I solved the problem by replacing scraping from a website to read from static tables.
It will require updating the dictionary every season, but it allowed me to quickly remove the error. 😄
